[2022-03-15 11:02:32,440] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-15 11:02:32,451] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-15 11:02:32,452] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 11:02:32,453] {taskinstance.py:1244} INFO - Starting attempt 20 of 20
[2022-03-15 11:02:32,453] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 11:02:32,466] {taskinstance.py:1264} INFO - Executing <Task(GlueJobOperator): glue_job> on 2022-03-13 00:00:00+00:00
[2022-03-15 11:02:32,474] {standard_task_runner.py:52} INFO - Started process 11900 to run task
[2022-03-15 11:02:32,486] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'glue_poc', 'glue_job', 'scheduled__2022-03-13T00:00:00+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/glue_poc.py', '--cfg-path', '/tmp/tmpyy8gzhis', '--error-file', '/tmp/tmpgb0s65ss']
[2022-03-15 11:02:32,493] {standard_task_runner.py:77} INFO - Job 273: Subtask glue_job
[2022-03-15 11:02:32,587] {logging_mixin.py:109} INFO - Running <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [running]> on host 26f80f9099ae
[2022-03-15 11:02:32,658] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=glue_poc
AIRFLOW_CTX_TASK_ID=glue_job
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-13T00:00:00+00:00
[2022-03-15 11:02:32,659] {glue.py:128} INFO - Initializing AWS Glue Job: glue_***_poc. Wait for completion: True
[2022-03-15 11:02:32,676] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-15 11:02:33,019] {glue.py:179} INFO - Job doesn't exist. Now creating and running AWS Glue Job
[2022-03-15 11:02:33,031] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-15 11:02:34,261] {glue.py:99} INFO - Iam Role Name: AWSGlueServiceRolePOC
[2022-03-15 11:02:34,264] {glue.py:210} ERROR - Failed to create aws glue job, error: Parameter validation failed:
Unknown parameter in input: "name", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
Unknown parameter in input: "age", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
[2022-03-15 11:02:34,265] {glue.py:124} ERROR - Failed to run aws glue job, error: Parameter validation failed:
Unknown parameter in input: "name", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
Unknown parameter in input: "age", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
[2022-03-15 11:02:34,266] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 174, in get_or_create_glue_job
    get_job_response = glue_client.get_job(JobName=self.job_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EntityNotFoundException: An error occurred (EntityNotFoundException) when calling the GetJob operation: Job with name: glue_***_poc not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 130, in execute
    glue_job_run = glue_job.initialize_job(self.script_args, self.run_job_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 120, in initialize_job
    job_name = self.get_or_create_glue_job()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 206, in get_or_create_glue_job
    **self.create_job_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 692, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 740, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "name", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
Unknown parameter in input: "age", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
[2022-03-15 11:02:34,292] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=glue_poc, task_id=glue_job, execution_date=20220313T000000, start_date=20220315T110232, end_date=20220315T110234
[2022-03-15 11:02:34,308] {standard_task_runner.py:92} ERROR - Failed to execute job 273 for task glue_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 174, in get_or_create_glue_job
    get_job_response = glue_client.get_job(JobName=self.job_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EntityNotFoundException: An error occurred (EntityNotFoundException) when calling the GetJob operation: Job with name: glue_***_poc not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 130, in execute
    glue_job_run = glue_job.initialize_job(self.script_args, self.run_job_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 120, in initialize_job
    job_name = self.get_or_create_glue_job()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 206, in get_or_create_glue_job
    **self.create_job_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 692, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 740, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "name", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
Unknown parameter in input: "age", must be one of: Name, Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, Tags, NotificationProperty, GlueVersion, NumberOfWorkers, WorkerType
[2022-03-15 11:02:34,355] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 11:02:34,393] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
