[2022-03-15 11:05:11,821] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-15 11:05:11,836] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-15 11:05:11,837] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 11:05:11,838] {taskinstance.py:1244} INFO - Starting attempt 21 of 21
[2022-03-15 11:05:11,839] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 11:05:11,856] {taskinstance.py:1264} INFO - Executing <Task(GlueJobOperator): glue_job> on 2022-03-13 00:00:00+00:00
[2022-03-15 11:05:11,862] {standard_task_runner.py:52} INFO - Started process 12115 to run task
[2022-03-15 11:05:11,866] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'glue_poc', 'glue_job', 'scheduled__2022-03-13T00:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/glue_poc.py', '--cfg-path', '/tmp/tmp5ko266em', '--error-file', '/tmp/tmpgs0yl3ma']
[2022-03-15 11:05:11,868] {standard_task_runner.py:77} INFO - Job 274: Subtask glue_job
[2022-03-15 11:05:12,027] {logging_mixin.py:109} INFO - Running <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [running]> on host 26f80f9099ae
[2022-03-15 11:05:12,143] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=glue_poc
AIRFLOW_CTX_TASK_ID=glue_job
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-13T00:00:00+00:00
[2022-03-15 11:05:12,146] {glue.py:128} INFO - Initializing AWS Glue Job: glue_***_poc. Wait for completion: True
[2022-03-15 11:05:12,161] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-15 11:05:12,646] {glue.py:179} INFO - Job doesn't exist. Now creating and running AWS Glue Job
[2022-03-15 11:05:12,665] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-15 11:05:13,917] {glue.py:99} INFO - Iam Role Name: AWSGlueServiceRolePOC
[2022-03-15 11:05:14,055] {glue.py:124} ERROR - Failed to run aws glue job, error: Parameter validation failed:
Unknown parameter in input: "name", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers
Unknown parameter in input: "age", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers
[2022-03-15 11:05:14,057] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 130, in execute
    glue_job_run = glue_job.initialize_job(self.script_args, self.run_job_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 121, in initialize_job
    job_run = glue_client.start_job_run(JobName=job_name, Arguments=script_arguments, **run_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 692, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 740, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "name", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers
Unknown parameter in input: "age", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers
[2022-03-15 11:05:14,083] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=glue_poc, task_id=glue_job, execution_date=20220313T000000, start_date=20220315T110511, end_date=20220315T110514
[2022-03-15 11:05:14,107] {standard_task_runner.py:92} ERROR - Failed to execute job 274 for task glue_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 130, in execute
    glue_job_run = glue_job.initialize_job(self.script_args, self.run_job_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 121, in initialize_job
    job_run = glue_client.start_job_run(JobName=job_name, Arguments=script_arguments, **run_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 692, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 740, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "name", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers
Unknown parameter in input: "age", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers
[2022-03-15 11:05:14,152] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 11:05:14,194] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
