[2022-03-15 12:49:32,153] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-15 12:49:32,171] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [queued]>
[2022-03-15 12:49:32,173] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 12:49:32,175] {taskinstance.py:1244} INFO - Starting attempt 24 of 24
[2022-03-15 12:49:32,176] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 12:49:32,198] {taskinstance.py:1264} INFO - Executing <Task(GlueJobOperator): glue_job> on 2022-03-13 00:00:00+00:00
[2022-03-15 12:49:32,207] {standard_task_runner.py:52} INFO - Started process 20592 to run task
[2022-03-15 12:49:32,215] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'glue_poc', 'glue_job', 'scheduled__2022-03-13T00:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/glue_poc.py', '--cfg-path', '/tmp/tmp2h662uog', '--error-file', '/tmp/tmppb1idude']
[2022-03-15 12:49:32,217] {standard_task_runner.py:77} INFO - Job 277: Subtask glue_job
[2022-03-15 12:49:32,303] {logging_mixin.py:109} INFO - Running <TaskInstance: glue_poc.glue_job scheduled__2022-03-13T00:00:00+00:00 [running]> on host 26f80f9099ae
[2022-03-15 12:49:32,372] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=glue_poc
AIRFLOW_CTX_TASK_ID=glue_job
AIRFLOW_CTX_EXECUTION_DATE=2022-03-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-13T00:00:00+00:00
[2022-03-15 12:49:32,374] {glue.py:128} INFO - Initializing AWS Glue Job: glue_***_poc. Wait for completion: True
[2022-03-15 12:49:32,387] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-15 12:49:33,051] {glue.py:179} INFO - Job doesn't exist. Now creating and running AWS Glue Job
[2022-03-15 12:49:33,062] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-03-15 12:49:34,151] {glue.py:99} INFO - Iam Role Name: AWSGlueServiceRolePOC
[2022-03-15 12:49:34,534] {glue.py:163} INFO - Polling for AWS Glue Job glue_***_poc current run state with status RUNNING
[2022-03-15 12:49:40,637] {glue.py:163} INFO - Polling for AWS Glue Job glue_***_poc current run state with status RUNNING
[2022-03-15 12:49:46,823] {glue.py:163} INFO - Polling for AWS Glue Job glue_***_poc current run state with status RUNNING
[2022-03-15 12:49:53,058] {glue.py:163} INFO - Polling for AWS Glue Job glue_***_poc current run state with status RUNNING
[2022-03-15 12:49:59,130] {glue.py:163} INFO - Polling for AWS Glue Job glue_***_poc current run state with status RUNNING
[2022-03-15 12:50:06,150] {glue.py:159} INFO - Exiting Job jr_7f683ab4f5efef81cd39208cf76eeae5cbbae97749a228cdb5355ef678ead09c Run State: FAILED
[2022-03-15 12:50:06,166] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 132, in execute
    glue_job_run = glue_job.job_completion(self.job_name, glue_job_run['JobRunId'])
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 160, in job_completion
    raise AirflowException(job_error_message)
airflow.exceptions.AirflowException: Exiting Job jr_7f683ab4f5efef81cd39208cf76eeae5cbbae97749a228cdb5355ef678ead09c Run State: FAILED
[2022-03-15 12:50:06,175] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=glue_poc, task_id=glue_job, execution_date=20220313T000000, start_date=20220315T124932, end_date=20220315T125006
[2022-03-15 12:50:06,194] {standard_task_runner.py:92} ERROR - Failed to execute job 277 for task glue_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 132, in execute
    glue_job_run = glue_job.job_completion(self.job_name, glue_job_run['JobRunId'])
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 160, in job_completion
    raise AirflowException(job_error_message)
airflow.exceptions.AirflowException: Exiting Job jr_7f683ab4f5efef81cd39208cf76eeae5cbbae97749a228cdb5355ef678ead09c Run State: FAILED
[2022-03-15 12:50:06,219] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 12:50:06,250] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
