[2022-02-28 09:39:56,282] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 09:39:56,294] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 09:39:56,295] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 09:39:56,296] {taskinstance.py:1244} INFO - Starting attempt 11 of 11
[2022-02-28 09:39:56,296] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 09:39:56,315] {taskinstance.py:1264} INFO - Executing <Task(S3CreateBucketOperator): create_bucket> on 2022-02-25 00:00:00+00:00
[2022-02-28 09:39:56,324] {standard_task_runner.py:52} INFO - Started process 23014 to run task
[2022-02-28 09:39:56,328] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_s3_connection', 'create_bucket', 'scheduled__2022-02-25T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpp1msp03v', '--error-file', '/tmp/tmp2w9hm7ry']
[2022-02-28 09:39:56,330] {standard_task_runner.py:77} INFO - Job 81: Subtask create_bucket
[2022-02-28 09:39:56,394] {logging_mixin.py:109} INFO - Running <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-02-28 09:39:56,458] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_s3_connection
AIRFLOW_CTX_TASK_ID=create_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T00:00:00+00:00
[2022-02-28 09:39:56,471] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-02-28 09:39:58,023] {s3.py:162} ERROR - Not Found
[2022-02-28 09:39:58,538] {s3.py:74} INFO - Created bucket with name: s3bucket-through-***-task
[2022-02-28 09:39:58,558] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=test_s3_connection, task_id=create_bucket, execution_date=20220225T000000, start_date=20220228T093956, end_date=20220228T093958
[2022-02-28 09:39:58,611] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 09:39:58,656] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
