[2022-02-28 08:51:35,391] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 08:51:35,417] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 08:51:35,421] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 08:51:35,424] {taskinstance.py:1244} INFO - Starting attempt 8 of 8
[2022-02-28 08:51:35,426] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 08:51:35,458] {taskinstance.py:1264} INFO - Executing <Task(S3CreateBucketOperator): create_bucket> on 2022-02-25 00:00:00+00:00
[2022-02-28 08:51:35,467] {standard_task_runner.py:52} INFO - Started process 19956 to run task
[2022-02-28 08:51:35,480] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_s3_connection', 'create_bucket', 'scheduled__2022-02-25T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmp97fugodf', '--error-file', '/tmp/tmps7478267']
[2022-02-28 08:51:35,486] {standard_task_runner.py:77} INFO - Job 72: Subtask create_bucket
[2022-02-28 08:51:35,584] {logging_mixin.py:109} INFO - Running <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-02-28 08:51:35,738] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_s3_connection
AIRFLOW_CTX_TASK_ID=create_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T00:00:00+00:00
[2022-02-28 08:51:35,763] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-02-28 08:51:37,362] {s3.py:162} ERROR - Not Found
[2022-02-28 08:51:37,829] {s3.py:74} INFO - Created bucket with name: s3bucket-through-***-task
[2022-02-28 08:51:37,846] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=test_s3_connection, task_id=create_bucket, execution_date=20220225T000000, start_date=20220228T085135, end_date=20220228T085137
[2022-02-28 08:51:37,915] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 08:51:37,963] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
